// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE670F367x8XqP48TcFSMSOzpIdg7Mzfc',
    appId: '1:541048534386:web:706825821941d8a56019eb',
    messagingSenderId: '541048534386',
    projectId: 'notesapp-43ab9',
    authDomain: 'notesapp-43ab9.firebaseapp.com',
    storageBucket: 'notesapp-43ab9.firebasestorage.app',
    measurementId: 'G-0D0J9FY5JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAetECokEy8yX3xmSL9YVWF1Myyi4HAzho',
    appId: '1:541048534386:android:e4f34d8d6df9a0e66019eb',
    messagingSenderId: '541048534386',
    projectId: 'notesapp-43ab9',
    storageBucket: 'notesapp-43ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYNq2r-n-8GxCQBl1icxpThTamyaUwRc',
    appId: '1:541048534386:ios:478d8c6fde3e35036019eb',
    messagingSenderId: '541048534386',
    projectId: 'notesapp-43ab9',
    storageBucket: 'notesapp-43ab9.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYNq2r-n-8GxCQBl1icxpThTamyaUwRc',
    appId: '1:541048534386:ios:478d8c6fde3e35036019eb',
    messagingSenderId: '541048534386',
    projectId: 'notesapp-43ab9',
    storageBucket: 'notesapp-43ab9.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE670F367x8XqP48TcFSMSOzpIdg7Mzfc',
    appId: '1:541048534386:web:49bf4f2f6df6c02c6019eb',
    messagingSenderId: '541048534386',
    projectId: 'notesapp-43ab9',
    authDomain: 'notesapp-43ab9.firebaseapp.com',
    storageBucket: 'notesapp-43ab9.firebasestorage.app',
    measurementId: 'G-FQYL8382J4',
  );
}
